#! /usr/bin/python

import os, argparse



# setup and parse arguments
parser = argparse.ArgumentParser(description='CS143 PA4 Testing Script')
parser.add_argument('-c', action='store_true', help='cgen debug enable')
parser.add_argument('-d', action='store_true', help='run diff')
parser.add_argument('-r', action='store_true', help='run reference only')
parser.add_argument('-g', action='store_true', help='garbage collector')
parser.add_argument('-t', action='store_true', help='gc test')
parser.add_argument('-T', action='store_true', help='additional gc test')
parser.add_argument('files', metavar='file', type=str, nargs='+'
	, help='cl testing files')

args = parser.parse_args()

print args

# begin testing script
print '\n>>>>> CS143 PA4 Testing Script <<<<<'

if not args.r:
	ret = os.system('make cgen')
	if ret != 0:
		print 'Exit due to compilation error.'
		exit(0)

for f in args.files:
	print 'File: %s' % f
	name = f.split('.')[0]
	
	os.system('rm -f %s.s' % name)
	os.system('rm -f %s_ref.s' % name)
	os.system('rm -f spim.out spim_ref.out')
	
	flags = '';
	if args.c:
		flags += '-c '
	if args.g:
		flags += '-g '
	if args.t:
		flags += '-t '
	if args.T:
		flags += '-T '
	
	ret = os.system('/usr/class/cs143/bin/coolc %s %s' % (flags, f))
	if ret != 0:
		print 'Compilation error. Exit,'
		exit(0)
		
	print 'Run reference solution'	
	os.system('mv %s.s %s_ref.s' % (name, name))
	os.system('/usr/class/cs143/bin/spim -stext 1048576 -file %s_ref.s > spim_ref.out 2>&1' % name)
	#os.system('/usr/class/cs143/bin/spim -file %s_ref.s > spim_ref.out 2>&1' % name );
	
	if not args.r:
		
		ret = os.system('./mycoolc %s %s' % (flags, f))
		
		if not ret:
			print 'Run our solution'
			os.system('/usr/class/cs143/bin/spim -stext 1048576 -file %s.s > spim.out 2>&1' % name) 
			#os.system('/usr/class/cs143/bin/spim -file %s.s > spim.out 2>&1' % name );	
			if args.d:
				os.system('diff spim_ref.out spim.out')
		
	

print '====================================\n'
