#! /usr/bin/python

import os, argparse



# setup and parse arguments
parser = argparse.ArgumentParser(description='CS143 PA4 Testing Script')
parser.add_argument('-c', action='store_true', help='cgen debug enable')
parser.add_argument('-d', action='store_true', help='run diff')
parser.add_argument('-r', action='store_true', help='run reference only')
parser.add_argument('files', metavar='file', type=str, nargs='+'
	, help='cl testing files')

args = parser.parse_args()

print args

# begin testing script
print '\n>>>>> CS143 PA4 Testing Script <<<<<'

if not args.r:
	ret = os.system('make cgen')
	if ret != 0:
		print 'Exit due to compilation error.'
		exit(0)

for f in args.files:
	print 'File: %s' % f
	name = f.split('.')[0]
	
	os.system('rm -f out/%s.s' % name)
	os.system('rm -f out/%s_ref.s' % name)
	os.system('rm -f spim.out spim_ref.out')
	
	ret = os.system('/usr/class/cs143/bin/coolc %s' % f)
	if ret != 0:
		print 'Compilation error. Exit,'
		exit(0)
		
	os.system('mv %s.s %s_ref.s' % (name, name))
	os.system('/usr/class/cs143/bin/spim -file %s_ref.s > spim_ref.out 2>&1' % name );
	
	if not args.r:
		if args.c:
			ret = os.system('./mycoolc -c %s' % f)
		else:
			ret = os.system('./mycoolc %s' % f)
		
		if not ret:
			os.system('/usr/class/cs143/bin/spim -file %s.s > spim.out 2>&1' % name );	
			if args.d:
				os.system('diff spim_ref.out spim.out')
		
	

print '====================================\n'
